import { GetStaticProps, InferGetStaticPropsType, NextPage } from "next";
import { useAuth } from "../../context/auth";
import Head from "next/head";
import { NextPageWithLayout } from "./_app";
import { ReactElement } from "react";
import Layout from "../../components/layout";
import { Post } from "../../types/post";
import { adminDB } from "../../firebase/server";
import PostItemCard from "../../components/post-item-card";

export const getStaticProps: GetStaticProps<{
  posts: Post[];
}> = async (context) => {
  const snap = await adminDB
    .collection(`posts`)
    .orderBy("createdAt", "desc")
    .limit(20)
    .get();
  const posts = snap.docs.map((doc) => doc.data() as Post);

  return {
    props: {
      posts,
    },
  };
};

const Home: NextPageWithLayout<
  InferGetStaticPropsType<typeof getStaticProps>
> = ({ posts }) => {
  const { user } = useAuth();

  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h2>最新の記事</h2>
        {posts.length ? (
          <ul className="space-y-3">
            {posts?.map((post) => (
              <li key={post.id}>
                <PostItemCard post={post} />
              </li>
            ))}
          </ul>
        ) : (
          <p>記事がありません</p>
        )}
      </main>
    </div>
  );
};

// componentsのlayoutを各ページで使用する機能
Home.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};

export default Home;
