import { NextPage } from "next";
import { useAuth } from "../../context/auth";
import Head from "next/head";
import { NextPageWithLayout } from "./_app";
import { ReactElement } from "react";
import Layout from "../../components/layout";

const Home: NextPageWithLayout = () => {
  const { user } = useAuth();

  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>トップページ</h1>
        <p>{user?.name}</p>
      </main>
    </div>
  );
};

// componentsのlayoutを各ページで使用する機能
Home.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};

export default Home;
