import { GetStaticProps, InferGetStaticPropsType, NextPage } from "next";
import { useAuth } from "../../context/auth";
import Head from "next/head";
import { NextPageWithLayout } from "./_app";
import { ReactElement } from "react";
import Layout from "../../components/layout";
import { Post } from "../../types/post";
import { adminDB } from "../../firebase/server";
import PostItemCard from "../../components/post-item-card";
import { Swiper, SwiperSlide } from "swiper/react";
import "swiper/css";
import { Navigation, Pagination, Keyboard } from "swiper";
import { ChevronLeftIcon, ChevronRightIcon } from "@heroicons/react/24/outline";

export const getStaticProps: GetStaticProps<{
  posts: Post[];
}> = async (context) => {
  const snap = await adminDB
    .collection(`posts`)
    .orderBy("createdAt", "desc")
    .limit(20)
    .get();
  const posts = snap.docs.map((doc) => doc.data() as Post);

  return {
    props: {
      posts,
    },
  };
};

const Home: NextPageWithLayout<
  InferGetStaticPropsType<typeof getStaticProps>
> = ({ posts }) => {
  const { user } = useAuth();

  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          <div className="relative">
            <Swiper
              modules={[Navigation, Pagination, Keyboard]}
              loop
              navigation={{
                nextEl: "#next",
                prevEl: "#prev",
              }}
              pagination={{
                el: "#pagination",
                bulletClass:
                  "w-2 h-2 rounded-full block bg-slate-300 cursor-pointer",
                bulletActiveClass: "!bg-blue-500",
                clickable: true,
              }}
              keyboard
              spaceBetween={50}
              slidesPerView={1}
            >
              {new Array(5).fill(null).map((_, index) => {
                return (
                  <SwiperSlide key={index}>
                    <div className="bg-slate-200 aspect-video grid place-items-center">
                      <p className="text-3xl font-bold text-blue-500">
                        {index}
                      </p>
                    </div>
                  </SwiperSlide>
                );
              })}
            </Swiper>
            <div
              className=" absolute p-4 top-1/2 z-10 -translate-y-1/2"
              id="prev"
            >
              <ChevronLeftIcon className="w-8 h-8 opacity-40" />
            </div>
            <div
              className=" absolute p-4 top-1/2 z-10 -translate-y-1/2 right-0"
              id="next"
            >
              <ChevronRightIcon className="w-8 h-8 opacity-40" />
            </div>
          </div>
          <div id="pagination" className="flex space-x-2 justify-center mt-4" />
        </div>

        <h2>最新の記事</h2>
        {posts.length ? (
          <ul className="space-y-3">
            {posts?.map((post) => (
              <li key={post.id}>
                <PostItemCard post={post} />
              </li>
            ))}
          </ul>
        ) : (
          <p>記事がありません</p>
        )}
      </main>
    </div>
  );
};

// componentsのlayoutを各ページで使用する機能
Home.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};

export default Home;
